# 中兴开发环境
spring:
  datasource:
    url: jdbc:oracle:thin:@192.168.30.113:1521/xe
    username: dom
    password: dom@123
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      read-only: false
      connection-timeout: 60000
      idle-timeout: 50000
      validation-timeout: 3000
      max-lifetime: 60000
      login-timeout: 5
      maximum-pool-size: 30
      minimum-idle: 10

  redis:
    host: 192.168.30.113
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 50
        min-idle: 0
        max-idle: 50
        max-wait: -1
    key-prefix: dev-

excluded:
  swagger-pages: /dom/csrf,/dom/,/dom/v2/api-docs
  pages: /dom/user/getToken, /dom/,/dom/cas,/dom/index,/dom/login,/dom/logout

sso:
  url: http://zxgd.softether.net:4443/cas
  home: http://192.168.30.140:8100/dom/

cas:
  serverUrlPrefix: "${sso.url}"
  serviceUrlPrefix: "http://192.168.30.140:8100/dom"
  casFilterUrlPattern: "/cas"
  loginUrlPattern: "/login"
  logoutUrlPattern: "/logout"
  successUrlPattern: "/index"
  serviceFront: "http://192.168.30.140:8199/index.html"

diboot:
  core:
    init-sql: false
  iam:
    init-sql: false
  component:
    file:
      init-sql: false
    scheduler:
      init-sql: false
    message:
      init-sql: false

mdm:
  person:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllPersonList?wsdl"
  org:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllOrgList?wsdl"
  extra-org:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllExtraOrgList?wsdl"
  emp-job:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllEmpJobInfoList?wsdl"
  supp:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllSuppList?wsdl"
  supp-contact:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllSuppContactsList?wsdl"
  person-plus:
    address: "http://esb.wzmtr.com:7003/mdmwebservice/ps/getAllPersonPlusList?wsdl"

local:
  base-url: http://192.168.30.140:8900/dom
  data-sync: off

minio:
  url: http://192.168.30.113:9000
  imgPath: http://192.168.30.113:9000
  accessKey: miniominio
  secretKey: miniominio

#乘务、eam、施工调度、行车调度
ocm:
  host: http://nocm.wzmtr.com:2443
eam:
  host: http://192.168.30.140:8002
csm:
  host: http://192.168.30.140:8005
odm:
  host: http://10.11.82.27:8181


open-api:
  csm:
    constructPlan: ${csm.host}/csm/constructPlan/open/getPlanList
    importantConstruct: ${csm.host}/csm/constructPlan/open/getImportantPlanList
    unsaturationConstruct: ${csm.host}/csm/report/open/getUnsaturationPlan
    planStatistics: ${csm.host}/csm/report/open/getPlanStatistics
    dispatchOrder: ${csm.host}/csm/dispatch/order/open/list
  odm:
    depotStatistics: ${odm.host}/api/statistics/anon/day
  acc:
    api-app-key: "EvbhN1NZFmsuFM0j1T3Fi3tKQAxpd52r"
    person-count: "http://dxp.wzmtr.com:9080/v2/ACC/ACC13"

pro:
  name: dom