CREATE TABLE DOM.SYS_OFFICE (
	ID VARCHAR2(64) NOT NULL,
	PARENT_ID VARCHAR2(64),
	PARENT_IDS VARCHAR2(2000),
	NAME NVARCHAR2(1000),
	TYPE CHAR(1),
	GRADE CHAR(1),
	SORT NUMBER,
	REMARKS VARCHAR2(255),
	USEABLE VARCHAR2(64),
	DEL_FLAG CHAR(1),
	CREATE_BY VARCHAR2(64),
	CREATE_DATE TIMESTAMP,
	UPDATE_BY VARCHAR2(64),
	UPDATE_DATE TIMESTAMP,
	AREA_ID VARCHAR2(200),
	NAMES VARCHAR2(2000)
);

CREATE TABLE DOM.SYS_ORG_USER (
    ID VARCHAR2(64),
	COMPANY_ID VARCHAR2(64),
	OFFICE_ID VARCHAR2(64),
	USER_ID VARCHAR2(256),
	OFFICE_NAME VARCHAR2(512),
	POSTCODE VARCHAR2(64),
	POSTNAME VARCHAR2(512),
	LATESTARRIDATE DATE,
	COMPANYNAME VARCHAR2(512),
	LEAVEDATE DATE,
	LEAVESTATUS VARCHAR2(64),
	DEPARTFULLPATH VARCHAR2(1024),
	JOBCATEGORY VARCHAR2(64),
	JOBGRADE VARCHAR2(64),
	ACTIVESTATUS VARCHAR2(64),
	JOBLEVEL VARCHAR2(64),
	JOBNAME VARCHAR2(256),
	JOBCATEGORYNAME VARCHAR2(256),
	JOBLEVELNAME VARCHAR2(128),
	JOBGRADENAME VARCHAR2(128),
	POSITIONLEVEL VARCHAR2(64),
	JOBLEVELDATE DATE,
	MDM_USER_ID VARCHAR2(256),
	OLDINFOID VARCHAR2(64),
	PROCRESULT VARCHAR2(64)
);

CREATE TABLE DOM.SYS_PERMISSION (
    ID VARCHAR2(32),
	NAME VARCHAR2(64),
	PARENT_ID VARCHAR2(32),
	PERM_CODE VARCHAR2(255),
	TYPE CHAR(1),
	URL VARCHAR2(255),
	SORT NUMBER,
	COMPONENT VARCHAR2(255),
	IS_SHOW CHAR(1),
	REMARKS VARCHAR2(255),
	STATUS CHAR(2),
	DEL_FLAG CHAR(1) DEFAULT 0,
	CREATE_BY VARCHAR2(64),
	CREATE_DATE TIMESTAMP (6),
	UPDATE_BY VARCHAR2(64),
	UPDATE_DATE TIMESTAMP (6),
	ICON VARCHAR2(255)
);

CREATE TABLE DOM.SYS_ROLE (
    ID VARCHAR2(32) NOT NULL ENABLE,
	ROLE_NAME VARCHAR2(128),
	ROLE_CODE VARCHAR2(128),
	REMARKS VARCHAR2(255),
	STATUS CHAR(2) DEFAULT 0,
	DEL_FLAG CHAR(1) DEFAULT 0,
	CREATE_BY VARCHAR2(64),
	CREATE_DATE TIMESTAMP (6) DEFAULT sysdate,
	UPDATE_BY VARCHAR2(64),
	UPDATE_DATE TIMESTAMP (6) DEFAULT sysdate,
	SORT NUMBER DEFAULT 0
);

CREATE TABLE DOM.SYS_ROLE_PERMISSION (
    ID VARCHAR2(32),
	ROLE_ID VARCHAR2(32),
	PERMISSION_ID VARCHAR2(32),
	DATA_RULE_IDS VARCHAR2(1024)
);

CREATE TABLE DOM.SYS_USER (
    ID VARCHAR2(64) NOT NULL ENABLE,
	LOGIN_NAME VARCHAR2(100),
	PASSWORD VARCHAR2(100),
	EXPIRED NUMBER DEFAULT 0,
	DISABLED NUMBER DEFAULT 0,
	NO VARCHAR2(64),
	COMPANY_ID VARCHAR2(64),
	OFFICE_ID VARCHAR2(64),
	NAME NVARCHAR2(100),
	EMAIL NVARCHAR2(200),
	PHONE VARCHAR2(200),
	MOBILE VARCHAR2(200),
	USER_TYPE CHAR(1) DEFAULT 3,
	LOGIN_FLAG CHAR(1),
	NEW_WORKER CHAR(1),
	PHOTO VARCHAR2(1000),
	BIRTH_DATE DATE,
	HIRE_DATE DATE,
	REMARKS NVARCHAR2(255),
	ORDER_NUM NUMBER DEFAULT 0,
	ROOM VARCHAR2(128),
	FLAGPOSITION VARCHAR2(64),
	DEL_FLAG CHAR(1) DEFAULT 0,
	CREATE_BY VARCHAR2(64),
	CREATE_DATE TIMESTAMP (6) DEFAULT sysdate,
	UPDATE_BY VARCHAR2(64),
	UPDATE_DATE TIMESTAMP (6) DEFAULT sysdate,
	PERSON_ID VARCHAR2(64) DEFAULT 0,
	C_OWNER CHAR(1),
	AGE NUMBER DEFAULT 0
);

CREATE TABLE DOM.SYS_USER_ROLE (
    ID VARCHAR2(32) NOT NULL ENABLE,
	USER_ID VARCHAR2(32),
	ROLE_ID VARCHAR2(32)
);

CREATE TABLE DOM.SYS_FILE (
	ID VARCHAR2(255),
	FILE_NAME VARCHAR2(255),
	OLD_NAME VARCHAR2(255),
	BUCKET VARCHAR2(255),
	URL VARCHAR2(255),
	CREATE_BY VARCHAR2(255),
	CREATE_TIME DATE DEFAULT sysdate 
);

CREATE TABLE DOM.SYS_DICT_TYPE (
	ID VARCHAR2(100) NOT NULL,
	CODE VARCHAR2(100),
	NAME VARCHAR2(100),
	REMARK VARCHAR2(100),
	STATUS NUMBER DEFAULT 0 NOT NULL,
	CREATE_DATE DATE DEFAULT sysdate,
	CREATE_BY VARCHAR2(100),
	UPDATE_DATE DATE DEFAULT sysdate,
	UPDATE_BY VARCHAR2(100),
	DEL_FLAG NUMBER DEFAULT 0 NOT NULL
);
COMMENT ON TABLE DOM.SYS_DICT_TYPE IS '字典类型表';
COMMENT ON COLUMN DOM.SYS_DICT_TYPE.ID IS 'id';
COMMENT ON COLUMN DOM.SYS_DICT_TYPE.CODE IS '编号';
COMMENT ON COLUMN DOM.SYS_DICT_TYPE.NAME IS '名称';
COMMENT ON COLUMN DOM.SYS_DICT_TYPE.REMARK IS '备注';
COMMENT ON COLUMN DOM.SYS_DICT_TYPE.STATUS IS '启用状态 0 启用 1 禁用';
ALTER TABLE DOM.SYS_DICT_TYPE MODIFY DEL_FLAG CHAR(1) DEFAULT 0 ;
ALTER TABLE DOM.SYS_DICT_TYPE MODIFY CODE VARCHAR2(100) NOT NULL;
ALTER TABLE DOM.SYS_DICT_TYPE MODIFY NAME VARCHAR2(100) NOT NULL;

CREATE TABLE DOM.SYS_DICT (
	ID VARCHAR2(100) NOT NULL,
	TYPE_CODE VARCHAR2(100) NOT NULL,
	CODE VARCHAR2(100) NOT NULL,
	NAME VARCHAR2(500) NOT NULL,
	REMARK VARCHAR2(100),
	STATUS CHAR(1) DEFAULT 0 NOT NULL,
	CREATE_DATE VARCHAR2(100) DEFAULT sysdate,
	CREATE_BY VARCHAR2(100),
	UPDATE_DATE VARCHAR2(100) DEFAULT sysdate,
	UPDATE_BY VARCHAR2(100),
	DEL_FLAG CHAR(1) DEFAULT 0 NOT NULL
);
COMMENT ON TABLE DOM.SYS_DICT IS '字典值表';
COMMENT ON COLUMN DOM.SYS_DICT.ID IS 'id';
COMMENT ON COLUMN DOM.SYS_DICT.TYPE_CODE IS '类型编号';
COMMENT ON COLUMN DOM.SYS_DICT.CODE IS '值编号';
COMMENT ON COLUMN DOM.SYS_DICT.NAME IS '值名称';
COMMENT ON COLUMN DOM.SYS_DICT.REMARK IS '备注';
ALTER TABLE DOM.SYS_DICT ADD SORT NUMBER DEFAULT 0;

CREATE TABLE DOM.SYS_STATION_ROLE (
	ID VARCHAR2(100) NOT NULL,
	STATION_CODE VARCHAR2(100),
	STATION_NAME VARCHAR2(100),
	START_TIME DATE,
	END_TIME DATE,
	CREATE_DATE DATE DEFAULT sysdate,
	CREATE_BY VARCHAR2(100),
	UPDATE_DATE DATE DEFAULT sysdate,
	UPDATE_BY VARCHAR2(100),
	DEL_FLAG CHAR(1) DEFAULT 0 NOT NULL
);
COMMENT ON TABLE DOM.SYS_STATION_ROLE IS '参数设置-审核站权限';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.ID IS 'ID';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.STATION_CODE IS '车站编号';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.STATION_NAME IS '车站名称';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.START_TIME IS '开始时间';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.END_TIME IS '结束时间';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.CREATE_DATE IS '新增时间';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.CREATE_BY IS '新增人';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.UPDATE_DATE IS '修改时间';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.UPDATE_BY IS '修改人';
COMMENT ON COLUMN DOM.SYS_STATION_ROLE.DEL_FLAG IS '删除标记';

CREATE TABLE DOM.SYS_DAILY_STATISTICS (
	ID VARCHAR2(100) NOT NULL,
	START_TIME DATE,
	END_TIME DATE,
	CREATE_DATE DATE DEFAULT sysdate,
	CREATE_BY VARCHAR2(100),
	UPDATE_DATE DATE DEFAULT sysdate,
	UPDATE_BY VARCHAR2(100),
	DEL_FLAG CHAR(1) DEFAULT 0 NOT NULL
);
COMMENT ON TABLE DOM.SYS_DAILY_STATISTICS IS '参数设置-日报统计参数设置';
COMMENT ON COLUMN DOM.SYS_DAILY_STATISTICS.ID IS 'ID';
COMMENT ON COLUMN DOM.SYS_DAILY_STATISTICS.START_TIME IS '开始时间';
COMMENT ON COLUMN DOM.SYS_DAILY_STATISTICS.END_TIME IS '结束时间';
COMMENT ON COLUMN DOM.SYS_DAILY_STATISTICS.CREATE_DATE IS '创建时间';
COMMENT ON COLUMN DOM.SYS_DAILY_STATISTICS.CREATE_BY IS '创建人';
COMMENT ON COLUMN DOM.SYS_DAILY_STATISTICS.UPDATE_DATE IS '修改时间';
COMMENT ON COLUMN DOM.SYS_DAILY_STATISTICS.UPDATE_BY IS '修改人';
COMMENT ON COLUMN DOM.SYS_DAILY_STATISTICS.DEL_FLAG IS '删除标记';
