# 项目相关配置
zxrail:
  security:
    # 系统登录方式 system_self_login: 系统自带登录; platform_sso: 平台sso
    loginType: not_support
    platformLogin:
      platformDomain: http://localhost:3000
      checkTokenPath: /oauth/check_token
      logoutPath: /token/logout
  cache:
    keyPrefix: zxrail-framework
# 数据源配置
mybatis-flex:
  datasource:
    master:
      type: hikari
      url: jdbc:mysql://127.0.0.1:3306/zxrail-demo
      username: root
      password: root
    slave:
      type: hikari
      url: jdbc:mysql://127.0.0.1:3306/zxrail-demo
      username: root
      password: root
# redis配置
spring:
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 1
    # 密码(如没有密码请注释掉)
    #    password: 123456
    # 连接超时时间
    timeout: 10s
    # 是否开启ssl
    ssl: false

# xxl-job 配置
xxl.job:
  # 执行器开关
  enabled: false
  # 调度中心地址：如调度中心集群部署存在多个地址则用逗号分隔。
  admin-addresses: http://localhost:9090/xxl-job-admin
  # 执行器通讯TOKEN：非空时启用
  access-token: default_token
  # 执行器AppName：执行器心跳注册分组依据；为空则关闭自动注册
  appname: xxl-job-executor
  # 执行器注册：默认IP:PORT
  address:
  # 执行器IP：默认自动获取IP
  ip:
  # 执行器端口号 执行器从9101开始往后写
  port: 9091
  # 执行器运行日志文件存储磁盘路径
  logpath: ./logs/xxl-job
  # 执行器日志文件保存天数：大于3生效
  logretentiondays: 30


# 日志配置
logging:
  level:
    com.zxrail: debug
    org.springframework: warn
#  config: classpath:logback-plus.xml
magic-api:
#  web:
server:
  port: 8082
